// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gpss.proto

package api;

public interface CloseRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:api.CloseRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.api.Session session = 1;</code>
   */
  boolean hasSession();
  /**
   * <code>.api.Session session = 1;</code>
   */
  api.Session getSession();
  /**
   * <code>.api.Session session = 1;</code>
   */
  api.SessionOrBuilder getSessionOrBuilder();
}
