// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gpss.proto

package api;

public interface ColumnsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:api.Columns)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .api.ColumnInfo Columns = 1;</code>
   */
  java.util.List<api.ColumnInfo> 
      getColumnsList();
  /**
   * <code>repeated .api.ColumnInfo Columns = 1;</code>
   */
  api.ColumnInfo getColumns(int index);
  /**
   * <code>repeated .api.ColumnInfo Columns = 1;</code>
   */
  int getColumnsCount();
  /**
   * <code>repeated .api.ColumnInfo Columns = 1;</code>
   */
  java.util.List<? extends api.ColumnInfoOrBuilder> 
      getColumnsOrBuilderList();
  /**
   * <code>repeated .api.ColumnInfo Columns = 1;</code>
   */
  api.ColumnInfoOrBuilder getColumnsOrBuilder(
      int index);
}
