// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gpss.proto

package api;

/**
 * Protobuf type {@code api.DBValue}
 */
public  final class DBValue extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:api.DBValue)
    DBValueOrBuilder {
private static final long serialVersionUID = 0L;
  // Use DBValue.newBuilder() to construct.
  private DBValue(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private DBValue() {
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private DBValue(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {
            dBTypeCase_ = 1;
            dBType_ = input.readInt32();
            break;
          }
          case 16: {
            dBTypeCase_ = 2;
            dBType_ = input.readInt64();
            break;
          }
          case 45: {
            dBTypeCase_ = 5;
            dBType_ = input.readFloat();
            break;
          }
          case 49: {
            dBTypeCase_ = 6;
            dBType_ = input.readDouble();
            break;
          }
          case 58: {
            java.lang.String s = input.readStringRequireUtf8();
            dBTypeCase_ = 7;
            dBType_ = s;
            break;
          }
          case 66: {
            dBTypeCase_ = 8;
            dBType_ = input.readBytes();
            break;
          }
          case 82: {
            com.google.protobuf.Timestamp.Builder subBuilder = null;
            if (dBTypeCase_ == 10) {
              subBuilder = ((com.google.protobuf.Timestamp) dBType_).toBuilder();
            }
            dBType_ =
                input.readMessage(com.google.protobuf.Timestamp.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((com.google.protobuf.Timestamp) dBType_);
              dBType_ = subBuilder.buildPartial();
            }
            dBTypeCase_ = 10;
            break;
          }
          case 88: {
            int rawValue = input.readEnum();
            dBTypeCase_ = 11;
            dBType_ = rawValue;
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return api.GpssOuterClass.internal_static_api_DBValue_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return api.GpssOuterClass.internal_static_api_DBValue_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            api.DBValue.class, api.DBValue.Builder.class);
  }

  private int dBTypeCase_ = 0;
  private java.lang.Object dBType_;
  public enum DBTypeCase
      implements com.google.protobuf.Internal.EnumLite {
    INT32VALUE(1),
    INT64VALUE(2),
    FLOAT32VALUE(5),
    FLOAT64VALUE(6),
    STRINGVALUE(7),
    BYTESVALUE(8),
    TIMESTAMPVALUE(10),
    NULLVALUE(11),
    DBTYPE_NOT_SET(0);
    private final int value;
    private DBTypeCase(int value) {
      this.value = value;
    }
    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static DBTypeCase valueOf(int value) {
      return forNumber(value);
    }

    public static DBTypeCase forNumber(int value) {
      switch (value) {
        case 1: return INT32VALUE;
        case 2: return INT64VALUE;
        case 5: return FLOAT32VALUE;
        case 6: return FLOAT64VALUE;
        case 7: return STRINGVALUE;
        case 8: return BYTESVALUE;
        case 10: return TIMESTAMPVALUE;
        case 11: return NULLVALUE;
        case 0: return DBTYPE_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public DBTypeCase
  getDBTypeCase() {
    return DBTypeCase.forNumber(
        dBTypeCase_);
  }

  public static final int INT32VALUE_FIELD_NUMBER = 1;
  /**
   * <code>int32 Int32Value = 1;</code>
   */
  public int getInt32Value() {
    if (dBTypeCase_ == 1) {
      return (java.lang.Integer) dBType_;
    }
    return 0;
  }

  public static final int INT64VALUE_FIELD_NUMBER = 2;
  /**
   * <code>int64 Int64Value = 2;</code>
   */
  public long getInt64Value() {
    if (dBTypeCase_ == 2) {
      return (java.lang.Long) dBType_;
    }
    return 0L;
  }

  public static final int FLOAT32VALUE_FIELD_NUMBER = 5;
  /**
   * <code>float Float32Value = 5;</code>
   */
  public float getFloat32Value() {
    if (dBTypeCase_ == 5) {
      return (java.lang.Float) dBType_;
    }
    return 0F;
  }

  public static final int FLOAT64VALUE_FIELD_NUMBER = 6;
  /**
   * <code>double Float64Value = 6;</code>
   */
  public double getFloat64Value() {
    if (dBTypeCase_ == 6) {
      return (java.lang.Double) dBType_;
    }
    return 0D;
  }

  public static final int STRINGVALUE_FIELD_NUMBER = 7;
  /**
   * <pre>
   * Includes types whose values are presented as string but are not a real string type in Greenplum; for example: macaddr, time with time zone, box, etc.
   * </pre>
   *
   * <code>string StringValue = 7;</code>
   */
  public java.lang.String getStringValue() {
    java.lang.Object ref = "";
    if (dBTypeCase_ == 7) {
      ref = dBType_;
    }
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (dBTypeCase_ == 7) {
        dBType_ = s;
      }
      return s;
    }
  }
  /**
   * <pre>
   * Includes types whose values are presented as string but are not a real string type in Greenplum; for example: macaddr, time with time zone, box, etc.
   * </pre>
   *
   * <code>string StringValue = 7;</code>
   */
  public com.google.protobuf.ByteString
      getStringValueBytes() {
    java.lang.Object ref = "";
    if (dBTypeCase_ == 7) {
      ref = dBType_;
    }
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      if (dBTypeCase_ == 7) {
        dBType_ = b;
      }
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int BYTESVALUE_FIELD_NUMBER = 8;
  /**
   * <code>bytes BytesValue = 8;</code>
   */
  public com.google.protobuf.ByteString getBytesValue() {
    if (dBTypeCase_ == 8) {
      return (com.google.protobuf.ByteString) dBType_;
    }
    return com.google.protobuf.ByteString.EMPTY;
  }

  public static final int TIMESTAMPVALUE_FIELD_NUMBER = 10;
  /**
   * <pre>
   * Time without timezone
   * </pre>
   *
   * <code>.google.protobuf.Timestamp TimeStampValue = 10;</code>
   */
  public boolean hasTimeStampValue() {
    return dBTypeCase_ == 10;
  }
  /**
   * <pre>
   * Time without timezone
   * </pre>
   *
   * <code>.google.protobuf.Timestamp TimeStampValue = 10;</code>
   */
  public com.google.protobuf.Timestamp getTimeStampValue() {
    if (dBTypeCase_ == 10) {
       return (com.google.protobuf.Timestamp) dBType_;
    }
    return com.google.protobuf.Timestamp.getDefaultInstance();
  }
  /**
   * <pre>
   * Time without timezone
   * </pre>
   *
   * <code>.google.protobuf.Timestamp TimeStampValue = 10;</code>
   */
  public com.google.protobuf.TimestampOrBuilder getTimeStampValueOrBuilder() {
    if (dBTypeCase_ == 10) {
       return (com.google.protobuf.Timestamp) dBType_;
    }
    return com.google.protobuf.Timestamp.getDefaultInstance();
  }

  public static final int NULLVALUE_FIELD_NUMBER = 11;
  /**
   * <code>.google.protobuf.NullValue NullValue = 11;</code>
   */
  public int getNullValueValue() {
    if (dBTypeCase_ == 11) {
      return (java.lang.Integer) dBType_;
    }
    return 0;
  }
  /**
   * <code>.google.protobuf.NullValue NullValue = 11;</code>
   */
  public com.google.protobuf.NullValue getNullValue() {
    if (dBTypeCase_ == 11) {
      @SuppressWarnings("deprecation")
      com.google.protobuf.NullValue result = com.google.protobuf.NullValue.valueOf(
          (java.lang.Integer) dBType_);
      return result == null ? com.google.protobuf.NullValue.UNRECOGNIZED : result;
    }
    return com.google.protobuf.NullValue.NULL_VALUE;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (dBTypeCase_ == 1) {
      output.writeInt32(
          1, (int)((java.lang.Integer) dBType_));
    }
    if (dBTypeCase_ == 2) {
      output.writeInt64(
          2, (long)((java.lang.Long) dBType_));
    }
    if (dBTypeCase_ == 5) {
      output.writeFloat(
          5, (float)((java.lang.Float) dBType_));
    }
    if (dBTypeCase_ == 6) {
      output.writeDouble(
          6, (double)((java.lang.Double) dBType_));
    }
    if (dBTypeCase_ == 7) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 7, dBType_);
    }
    if (dBTypeCase_ == 8) {
      output.writeBytes(
          8, (com.google.protobuf.ByteString) dBType_);
    }
    if (dBTypeCase_ == 10) {
      output.writeMessage(10, (com.google.protobuf.Timestamp) dBType_);
    }
    if (dBTypeCase_ == 11) {
      output.writeEnum(11, ((java.lang.Integer) dBType_));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (dBTypeCase_ == 1) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(
            1, (int)((java.lang.Integer) dBType_));
    }
    if (dBTypeCase_ == 2) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(
            2, (long)((java.lang.Long) dBType_));
    }
    if (dBTypeCase_ == 5) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(
            5, (float)((java.lang.Float) dBType_));
    }
    if (dBTypeCase_ == 6) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(
            6, (double)((java.lang.Double) dBType_));
    }
    if (dBTypeCase_ == 7) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, dBType_);
    }
    if (dBTypeCase_ == 8) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(
            8, (com.google.protobuf.ByteString) dBType_);
    }
    if (dBTypeCase_ == 10) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(10, (com.google.protobuf.Timestamp) dBType_);
    }
    if (dBTypeCase_ == 11) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(11, ((java.lang.Integer) dBType_));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof api.DBValue)) {
      return super.equals(obj);
    }
    api.DBValue other = (api.DBValue) obj;

    boolean result = true;
    result = result && getDBTypeCase().equals(
        other.getDBTypeCase());
    if (!result) return false;
    switch (dBTypeCase_) {
      case 1:
        result = result && (getInt32Value()
            == other.getInt32Value());
        break;
      case 2:
        result = result && (getInt64Value()
            == other.getInt64Value());
        break;
      case 5:
        result = result && (
            java.lang.Float.floatToIntBits(getFloat32Value())
            == java.lang.Float.floatToIntBits(
                other.getFloat32Value()));
        break;
      case 6:
        result = result && (
            java.lang.Double.doubleToLongBits(getFloat64Value())
            == java.lang.Double.doubleToLongBits(
                other.getFloat64Value()));
        break;
      case 7:
        result = result && getStringValue()
            .equals(other.getStringValue());
        break;
      case 8:
        result = result && getBytesValue()
            .equals(other.getBytesValue());
        break;
      case 10:
        result = result && getTimeStampValue()
            .equals(other.getTimeStampValue());
        break;
      case 11:
        result = result && getNullValueValue()
            == other.getNullValueValue();
        break;
      case 0:
      default:
    }
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    switch (dBTypeCase_) {
      case 1:
        hash = (37 * hash) + INT32VALUE_FIELD_NUMBER;
        hash = (53 * hash) + getInt32Value();
        break;
      case 2:
        hash = (37 * hash) + INT64VALUE_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getInt64Value());
        break;
      case 5:
        hash = (37 * hash) + FLOAT32VALUE_FIELD_NUMBER;
        hash = (53 * hash) + java.lang.Float.floatToIntBits(
            getFloat32Value());
        break;
      case 6:
        hash = (37 * hash) + FLOAT64VALUE_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            java.lang.Double.doubleToLongBits(getFloat64Value()));
        break;
      case 7:
        hash = (37 * hash) + STRINGVALUE_FIELD_NUMBER;
        hash = (53 * hash) + getStringValue().hashCode();
        break;
      case 8:
        hash = (37 * hash) + BYTESVALUE_FIELD_NUMBER;
        hash = (53 * hash) + getBytesValue().hashCode();
        break;
      case 10:
        hash = (37 * hash) + TIMESTAMPVALUE_FIELD_NUMBER;
        hash = (53 * hash) + getTimeStampValue().hashCode();
        break;
      case 11:
        hash = (37 * hash) + NULLVALUE_FIELD_NUMBER;
        hash = (53 * hash) + getNullValueValue();
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static api.DBValue parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static api.DBValue parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static api.DBValue parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static api.DBValue parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static api.DBValue parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static api.DBValue parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static api.DBValue parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static api.DBValue parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static api.DBValue parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static api.DBValue parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static api.DBValue parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static api.DBValue parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(api.DBValue prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code api.DBValue}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:api.DBValue)
      api.DBValueOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return api.GpssOuterClass.internal_static_api_DBValue_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return api.GpssOuterClass.internal_static_api_DBValue_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              api.DBValue.class, api.DBValue.Builder.class);
    }

    // Construct using api.DBValue.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      dBTypeCase_ = 0;
      dBType_ = null;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return api.GpssOuterClass.internal_static_api_DBValue_descriptor;
    }

    @java.lang.Override
    public api.DBValue getDefaultInstanceForType() {
      return api.DBValue.getDefaultInstance();
    }

    @java.lang.Override
    public api.DBValue build() {
      api.DBValue result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public api.DBValue buildPartial() {
      api.DBValue result = new api.DBValue(this);
      if (dBTypeCase_ == 1) {
        result.dBType_ = dBType_;
      }
      if (dBTypeCase_ == 2) {
        result.dBType_ = dBType_;
      }
      if (dBTypeCase_ == 5) {
        result.dBType_ = dBType_;
      }
      if (dBTypeCase_ == 6) {
        result.dBType_ = dBType_;
      }
      if (dBTypeCase_ == 7) {
        result.dBType_ = dBType_;
      }
      if (dBTypeCase_ == 8) {
        result.dBType_ = dBType_;
      }
      if (dBTypeCase_ == 10) {
        if (timeStampValueBuilder_ == null) {
          result.dBType_ = dBType_;
        } else {
          result.dBType_ = timeStampValueBuilder_.build();
        }
      }
      if (dBTypeCase_ == 11) {
        result.dBType_ = dBType_;
      }
      result.dBTypeCase_ = dBTypeCase_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof api.DBValue) {
        return mergeFrom((api.DBValue)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(api.DBValue other) {
      if (other == api.DBValue.getDefaultInstance()) return this;
      switch (other.getDBTypeCase()) {
        case INT32VALUE: {
          setInt32Value(other.getInt32Value());
          break;
        }
        case INT64VALUE: {
          setInt64Value(other.getInt64Value());
          break;
        }
        case FLOAT32VALUE: {
          setFloat32Value(other.getFloat32Value());
          break;
        }
        case FLOAT64VALUE: {
          setFloat64Value(other.getFloat64Value());
          break;
        }
        case STRINGVALUE: {
          dBTypeCase_ = 7;
          dBType_ = other.dBType_;
          onChanged();
          break;
        }
        case BYTESVALUE: {
          setBytesValue(other.getBytesValue());
          break;
        }
        case TIMESTAMPVALUE: {
          mergeTimeStampValue(other.getTimeStampValue());
          break;
        }
        case NULLVALUE: {
          setNullValueValue(other.getNullValueValue());
          break;
        }
        case DBTYPE_NOT_SET: {
          break;
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      api.DBValue parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (api.DBValue) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int dBTypeCase_ = 0;
    private java.lang.Object dBType_;
    public DBTypeCase
        getDBTypeCase() {
      return DBTypeCase.forNumber(
          dBTypeCase_);
    }

    public Builder clearDBType() {
      dBTypeCase_ = 0;
      dBType_ = null;
      onChanged();
      return this;
    }


    /**
     * <code>int32 Int32Value = 1;</code>
     */
    public int getInt32Value() {
      if (dBTypeCase_ == 1) {
        return (java.lang.Integer) dBType_;
      }
      return 0;
    }
    /**
     * <code>int32 Int32Value = 1;</code>
     */
    public Builder setInt32Value(int value) {
      dBTypeCase_ = 1;
      dBType_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 Int32Value = 1;</code>
     */
    public Builder clearInt32Value() {
      if (dBTypeCase_ == 1) {
        dBTypeCase_ = 0;
        dBType_ = null;
        onChanged();
      }
      return this;
    }

    /**
     * <code>int64 Int64Value = 2;</code>
     */
    public long getInt64Value() {
      if (dBTypeCase_ == 2) {
        return (java.lang.Long) dBType_;
      }
      return 0L;
    }
    /**
     * <code>int64 Int64Value = 2;</code>
     */
    public Builder setInt64Value(long value) {
      dBTypeCase_ = 2;
      dBType_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 Int64Value = 2;</code>
     */
    public Builder clearInt64Value() {
      if (dBTypeCase_ == 2) {
        dBTypeCase_ = 0;
        dBType_ = null;
        onChanged();
      }
      return this;
    }

    /**
     * <code>float Float32Value = 5;</code>
     */
    public float getFloat32Value() {
      if (dBTypeCase_ == 5) {
        return (java.lang.Float) dBType_;
      }
      return 0F;
    }
    /**
     * <code>float Float32Value = 5;</code>
     */
    public Builder setFloat32Value(float value) {
      dBTypeCase_ = 5;
      dBType_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>float Float32Value = 5;</code>
     */
    public Builder clearFloat32Value() {
      if (dBTypeCase_ == 5) {
        dBTypeCase_ = 0;
        dBType_ = null;
        onChanged();
      }
      return this;
    }

    /**
     * <code>double Float64Value = 6;</code>
     */
    public double getFloat64Value() {
      if (dBTypeCase_ == 6) {
        return (java.lang.Double) dBType_;
      }
      return 0D;
    }
    /**
     * <code>double Float64Value = 6;</code>
     */
    public Builder setFloat64Value(double value) {
      dBTypeCase_ = 6;
      dBType_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>double Float64Value = 6;</code>
     */
    public Builder clearFloat64Value() {
      if (dBTypeCase_ == 6) {
        dBTypeCase_ = 0;
        dBType_ = null;
        onChanged();
      }
      return this;
    }

    /**
     * <pre>
     * Includes types whose values are presented as string but are not a real string type in Greenplum; for example: macaddr, time with time zone, box, etc.
     * </pre>
     *
     * <code>string StringValue = 7;</code>
     */
    public java.lang.String getStringValue() {
      java.lang.Object ref = "";
      if (dBTypeCase_ == 7) {
        ref = dBType_;
      }
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (dBTypeCase_ == 7) {
          dBType_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Includes types whose values are presented as string but are not a real string type in Greenplum; for example: macaddr, time with time zone, box, etc.
     * </pre>
     *
     * <code>string StringValue = 7;</code>
     */
    public com.google.protobuf.ByteString
        getStringValueBytes() {
      java.lang.Object ref = "";
      if (dBTypeCase_ == 7) {
        ref = dBType_;
      }
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        if (dBTypeCase_ == 7) {
          dBType_ = b;
        }
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Includes types whose values are presented as string but are not a real string type in Greenplum; for example: macaddr, time with time zone, box, etc.
     * </pre>
     *
     * <code>string StringValue = 7;</code>
     */
    public Builder setStringValue(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  dBTypeCase_ = 7;
      dBType_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Includes types whose values are presented as string but are not a real string type in Greenplum; for example: macaddr, time with time zone, box, etc.
     * </pre>
     *
     * <code>string StringValue = 7;</code>
     */
    public Builder clearStringValue() {
      if (dBTypeCase_ == 7) {
        dBTypeCase_ = 0;
        dBType_ = null;
        onChanged();
      }
      return this;
    }
    /**
     * <pre>
     * Includes types whose values are presented as string but are not a real string type in Greenplum; for example: macaddr, time with time zone, box, etc.
     * </pre>
     *
     * <code>string StringValue = 7;</code>
     */
    public Builder setStringValueBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      dBTypeCase_ = 7;
      dBType_ = value;
      onChanged();
      return this;
    }

    /**
     * <code>bytes BytesValue = 8;</code>
     */
    public com.google.protobuf.ByteString getBytesValue() {
      if (dBTypeCase_ == 8) {
        return (com.google.protobuf.ByteString) dBType_;
      }
      return com.google.protobuf.ByteString.EMPTY;
    }
    /**
     * <code>bytes BytesValue = 8;</code>
     */
    public Builder setBytesValue(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  dBTypeCase_ = 8;
      dBType_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bytes BytesValue = 8;</code>
     */
    public Builder clearBytesValue() {
      if (dBTypeCase_ == 8) {
        dBTypeCase_ = 0;
        dBType_ = null;
        onChanged();
      }
      return this;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> timeStampValueBuilder_;
    /**
     * <pre>
     * Time without timezone
     * </pre>
     *
     * <code>.google.protobuf.Timestamp TimeStampValue = 10;</code>
     */
    public boolean hasTimeStampValue() {
      return dBTypeCase_ == 10;
    }
    /**
     * <pre>
     * Time without timezone
     * </pre>
     *
     * <code>.google.protobuf.Timestamp TimeStampValue = 10;</code>
     */
    public com.google.protobuf.Timestamp getTimeStampValue() {
      if (timeStampValueBuilder_ == null) {
        if (dBTypeCase_ == 10) {
          return (com.google.protobuf.Timestamp) dBType_;
        }
        return com.google.protobuf.Timestamp.getDefaultInstance();
      } else {
        if (dBTypeCase_ == 10) {
          return timeStampValueBuilder_.getMessage();
        }
        return com.google.protobuf.Timestamp.getDefaultInstance();
      }
    }
    /**
     * <pre>
     * Time without timezone
     * </pre>
     *
     * <code>.google.protobuf.Timestamp TimeStampValue = 10;</code>
     */
    public Builder setTimeStampValue(com.google.protobuf.Timestamp value) {
      if (timeStampValueBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        dBType_ = value;
        onChanged();
      } else {
        timeStampValueBuilder_.setMessage(value);
      }
      dBTypeCase_ = 10;
      return this;
    }
    /**
     * <pre>
     * Time without timezone
     * </pre>
     *
     * <code>.google.protobuf.Timestamp TimeStampValue = 10;</code>
     */
    public Builder setTimeStampValue(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      if (timeStampValueBuilder_ == null) {
        dBType_ = builderForValue.build();
        onChanged();
      } else {
        timeStampValueBuilder_.setMessage(builderForValue.build());
      }
      dBTypeCase_ = 10;
      return this;
    }
    /**
     * <pre>
     * Time without timezone
     * </pre>
     *
     * <code>.google.protobuf.Timestamp TimeStampValue = 10;</code>
     */
    public Builder mergeTimeStampValue(com.google.protobuf.Timestamp value) {
      if (timeStampValueBuilder_ == null) {
        if (dBTypeCase_ == 10 &&
            dBType_ != com.google.protobuf.Timestamp.getDefaultInstance()) {
          dBType_ = com.google.protobuf.Timestamp.newBuilder((com.google.protobuf.Timestamp) dBType_)
              .mergeFrom(value).buildPartial();
        } else {
          dBType_ = value;
        }
        onChanged();
      } else {
        if (dBTypeCase_ == 10) {
          timeStampValueBuilder_.mergeFrom(value);
        }
        timeStampValueBuilder_.setMessage(value);
      }
      dBTypeCase_ = 10;
      return this;
    }
    /**
     * <pre>
     * Time without timezone
     * </pre>
     *
     * <code>.google.protobuf.Timestamp TimeStampValue = 10;</code>
     */
    public Builder clearTimeStampValue() {
      if (timeStampValueBuilder_ == null) {
        if (dBTypeCase_ == 10) {
          dBTypeCase_ = 0;
          dBType_ = null;
          onChanged();
        }
      } else {
        if (dBTypeCase_ == 10) {
          dBTypeCase_ = 0;
          dBType_ = null;
        }
        timeStampValueBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * Time without timezone
     * </pre>
     *
     * <code>.google.protobuf.Timestamp TimeStampValue = 10;</code>
     */
    public com.google.protobuf.Timestamp.Builder getTimeStampValueBuilder() {
      return getTimeStampValueFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * Time without timezone
     * </pre>
     *
     * <code>.google.protobuf.Timestamp TimeStampValue = 10;</code>
     */
    public com.google.protobuf.TimestampOrBuilder getTimeStampValueOrBuilder() {
      if ((dBTypeCase_ == 10) && (timeStampValueBuilder_ != null)) {
        return timeStampValueBuilder_.getMessageOrBuilder();
      } else {
        if (dBTypeCase_ == 10) {
          return (com.google.protobuf.Timestamp) dBType_;
        }
        return com.google.protobuf.Timestamp.getDefaultInstance();
      }
    }
    /**
     * <pre>
     * Time without timezone
     * </pre>
     *
     * <code>.google.protobuf.Timestamp TimeStampValue = 10;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
        getTimeStampValueFieldBuilder() {
      if (timeStampValueBuilder_ == null) {
        if (!(dBTypeCase_ == 10)) {
          dBType_ = com.google.protobuf.Timestamp.getDefaultInstance();
        }
        timeStampValueBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                (com.google.protobuf.Timestamp) dBType_,
                getParentForChildren(),
                isClean());
        dBType_ = null;
      }
      dBTypeCase_ = 10;
      onChanged();;
      return timeStampValueBuilder_;
    }

    /**
     * <code>.google.protobuf.NullValue NullValue = 11;</code>
     */
    public int getNullValueValue() {
      if (dBTypeCase_ == 11) {
        return ((java.lang.Integer) dBType_).intValue();
      }
      return 0;
    }
    /**
     * <code>.google.protobuf.NullValue NullValue = 11;</code>
     */
    public Builder setNullValueValue(int value) {
      dBTypeCase_ = 11;
      dBType_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.NullValue NullValue = 11;</code>
     */
    public com.google.protobuf.NullValue getNullValue() {
      if (dBTypeCase_ == 11) {
        @SuppressWarnings("deprecation")
        com.google.protobuf.NullValue result = com.google.protobuf.NullValue.valueOf(
            (java.lang.Integer) dBType_);
        return result == null ? com.google.protobuf.NullValue.UNRECOGNIZED : result;
      }
      return com.google.protobuf.NullValue.NULL_VALUE;
    }
    /**
     * <code>.google.protobuf.NullValue NullValue = 11;</code>
     */
    public Builder setNullValue(com.google.protobuf.NullValue value) {
      if (value == null) {
        throw new NullPointerException();
      }
      dBTypeCase_ = 11;
      dBType_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.NullValue NullValue = 11;</code>
     */
    public Builder clearNullValue() {
      if (dBTypeCase_ == 11) {
        dBTypeCase_ = 0;
        dBType_ = null;
        onChanged();
      }
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:api.DBValue)
  }

  // @@protoc_insertion_point(class_scope:api.DBValue)
  private static final api.DBValue DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new api.DBValue();
  }

  public static api.DBValue getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<DBValue>
      PARSER = new com.google.protobuf.AbstractParser<DBValue>() {
    @java.lang.Override
    public DBValue parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new DBValue(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<DBValue> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<DBValue> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public api.DBValue getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

