// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gpss.proto

package api;

public interface DescribeTableRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:api.DescribeTableRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.api.Session Session = 1;</code>
   */
  boolean hasSession();
  /**
   * <code>.api.Session Session = 1;</code>
   */
  api.Session getSession();
  /**
   * <code>.api.Session Session = 1;</code>
   */
  api.SessionOrBuilder getSessionOrBuilder();

  /**
   * <code>string SchemaName = 2;</code>
   */
  java.lang.String getSchemaName();
  /**
   * <code>string SchemaName = 2;</code>
   */
  com.google.protobuf.ByteString
      getSchemaNameBytes();

  /**
   * <code>string TableName = 3;</code>
   */
  java.lang.String getTableName();
  /**
   * <code>string TableName = 3;</code>
   */
  com.google.protobuf.ByteString
      getTableNameBytes();
}
