// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gpss.proto

package api;

/**
 * <pre>
 * Open service Request message
 * </pre>
 *
 * Protobuf type {@code api.OpenRequest}
 */
public  final class OpenRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:api.OpenRequest)
    OpenRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use OpenRequest.newBuilder() to construct.
  private OpenRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private OpenRequest() {
    schemaName_ = "";
    tableName_ = "";
    preSQL_ = "";
    postSQL_ = "";
    timeout_ = 0;
    encoding_ = "";
    stagingSchema_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private OpenRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            api.Session.Builder subBuilder = null;
            if (session_ != null) {
              subBuilder = session_.toBuilder();
            }
            session_ = input.readMessage(api.Session.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(session_);
              session_ = subBuilder.buildPartial();
            }

            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            schemaName_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            tableName_ = s;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            preSQL_ = s;
            break;
          }
          case 42: {
            java.lang.String s = input.readStringRequireUtf8();

            postSQL_ = s;
            break;
          }
          case 48: {

            timeout_ = input.readInt32();
            break;
          }
          case 58: {
            java.lang.String s = input.readStringRequireUtf8();

            encoding_ = s;
            break;
          }
          case 66: {
            java.lang.String s = input.readStringRequireUtf8();

            stagingSchema_ = s;
            break;
          }
          case 802: {
            api.InsertOption.Builder subBuilder = null;
            if (optionCase_ == 100) {
              subBuilder = ((api.InsertOption) option_).toBuilder();
            }
            option_ =
                input.readMessage(api.InsertOption.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((api.InsertOption) option_);
              option_ = subBuilder.buildPartial();
            }
            optionCase_ = 100;
            break;
          }
          case 810: {
            api.UpdateOption.Builder subBuilder = null;
            if (optionCase_ == 101) {
              subBuilder = ((api.UpdateOption) option_).toBuilder();
            }
            option_ =
                input.readMessage(api.UpdateOption.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((api.UpdateOption) option_);
              option_ = subBuilder.buildPartial();
            }
            optionCase_ = 101;
            break;
          }
          case 818: {
            api.MergeOption.Builder subBuilder = null;
            if (optionCase_ == 102) {
              subBuilder = ((api.MergeOption) option_).toBuilder();
            }
            option_ =
                input.readMessage(api.MergeOption.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((api.MergeOption) option_);
              option_ = subBuilder.buildPartial();
            }
            optionCase_ = 102;
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return api.GpssOuterClass.internal_static_api_OpenRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return api.GpssOuterClass.internal_static_api_OpenRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            api.OpenRequest.class, api.OpenRequest.Builder.class);
  }

  private int optionCase_ = 0;
  private java.lang.Object option_;
  public enum OptionCase
      implements com.google.protobuf.Internal.EnumLite {
    INSERTOPTION(100),
    UPDATEOPTION(101),
    MERGEOPTION(102),
    OPTION_NOT_SET(0);
    private final int value;
    private OptionCase(int value) {
      this.value = value;
    }
    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static OptionCase valueOf(int value) {
      return forNumber(value);
    }

    public static OptionCase forNumber(int value) {
      switch (value) {
        case 100: return INSERTOPTION;
        case 101: return UPDATEOPTION;
        case 102: return MERGEOPTION;
        case 0: return OPTION_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public OptionCase
  getOptionCase() {
    return OptionCase.forNumber(
        optionCase_);
  }

  public static final int SESSION_FIELD_NUMBER = 1;
  private api.Session session_;
  /**
   * <pre>
   * Session ID returned by Connect
   * </pre>
   *
   * <code>.api.Session Session = 1;</code>
   */
  public boolean hasSession() {
    return session_ != null;
  }
  /**
   * <pre>
   * Session ID returned by Connect
   * </pre>
   *
   * <code>.api.Session Session = 1;</code>
   */
  public api.Session getSession() {
    return session_ == null ? api.Session.getDefaultInstance() : session_;
  }
  /**
   * <pre>
   * Session ID returned by Connect
   * </pre>
   *
   * <code>.api.Session Session = 1;</code>
   */
  public api.SessionOrBuilder getSessionOrBuilder() {
    return getSession();
  }

  public static final int SCHEMANAME_FIELD_NUMBER = 2;
  private volatile java.lang.Object schemaName_;
  /**
   * <pre>
   * Name of the Greenplum Database schema
   * </pre>
   *
   * <code>string SchemaName = 2;</code>
   */
  public java.lang.String getSchemaName() {
    java.lang.Object ref = schemaName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      schemaName_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Name of the Greenplum Database schema
   * </pre>
   *
   * <code>string SchemaName = 2;</code>
   */
  public com.google.protobuf.ByteString
      getSchemaNameBytes() {
    java.lang.Object ref = schemaName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      schemaName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TABLENAME_FIELD_NUMBER = 3;
  private volatile java.lang.Object tableName_;
  /**
   * <pre>
   * Name of the Greenplum Database table
   * </pre>
   *
   * <code>string TableName = 3;</code>
   */
  public java.lang.String getTableName() {
    java.lang.Object ref = tableName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      tableName_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Name of the Greenplum Database table
   * </pre>
   *
   * <code>string TableName = 3;</code>
   */
  public com.google.protobuf.ByteString
      getTableNameBytes() {
    java.lang.Object ref = tableName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      tableName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PRESQL_FIELD_NUMBER = 4;
  private volatile java.lang.Object preSQL_;
  /**
   * <pre>
   * SQL to execute before gpss loads the data
   * </pre>
   *
   * <code>string PreSQL = 4;</code>
   */
  public java.lang.String getPreSQL() {
    java.lang.Object ref = preSQL_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      preSQL_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * SQL to execute before gpss loads the data
   * </pre>
   *
   * <code>string PreSQL = 4;</code>
   */
  public com.google.protobuf.ByteString
      getPreSQLBytes() {
    java.lang.Object ref = preSQL_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      preSQL_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int POSTSQL_FIELD_NUMBER = 5;
  private volatile java.lang.Object postSQL_;
  /**
   * <pre>
   * SQL to execute after gpss loads the data
   * </pre>
   *
   * <code>string PostSQL = 5;</code>
   */
  public java.lang.String getPostSQL() {
    java.lang.Object ref = postSQL_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      postSQL_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * SQL to execute after gpss loads the data
   * </pre>
   *
   * <code>string PostSQL = 5;</code>
   */
  public com.google.protobuf.ByteString
      getPostSQLBytes() {
    java.lang.Object ref = postSQL_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      postSQL_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TIMEOUT_FIELD_NUMBER = 6;
  private int timeout_;
  /**
   * <pre>
   * Time to wait before aborting the operation (seconds); not supported
   * </pre>
   *
   * <code>int32 Timeout = 6;</code>
   */
  public int getTimeout() {
    return timeout_;
  }

  public static final int ENCODING_FIELD_NUMBER = 7;
  private volatile java.lang.Object encoding_;
  /**
   * <pre>
   * Encoding of text data; not supported
   * </pre>
   *
   * <code>string Encoding = 7;</code>
   */
  public java.lang.String getEncoding() {
    java.lang.Object ref = encoding_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      encoding_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Encoding of text data; not supported
   * </pre>
   *
   * <code>string Encoding = 7;</code>
   */
  public com.google.protobuf.ByteString
      getEncodingBytes() {
    java.lang.Object ref = encoding_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      encoding_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int STAGINGSCHEMA_FIELD_NUMBER = 8;
  private volatile java.lang.Object stagingSchema_;
  /**
   * <pre>
   * Schema in which gpss creates external and temp tables; default is to create these tables in the same schema as the target table
   * </pre>
   *
   * <code>string StagingSchema = 8;</code>
   */
  public java.lang.String getStagingSchema() {
    java.lang.Object ref = stagingSchema_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      stagingSchema_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Schema in which gpss creates external and temp tables; default is to create these tables in the same schema as the target table
   * </pre>
   *
   * <code>string StagingSchema = 8;</code>
   */
  public com.google.protobuf.ByteString
      getStagingSchemaBytes() {
    java.lang.Object ref = stagingSchema_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      stagingSchema_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int INSERTOPTION_FIELD_NUMBER = 100;
  /**
   * <code>.api.InsertOption InsertOption = 100;</code>
   */
  public boolean hasInsertOption() {
    return optionCase_ == 100;
  }
  /**
   * <code>.api.InsertOption InsertOption = 100;</code>
   */
  public api.InsertOption getInsertOption() {
    if (optionCase_ == 100) {
       return (api.InsertOption) option_;
    }
    return api.InsertOption.getDefaultInstance();
  }
  /**
   * <code>.api.InsertOption InsertOption = 100;</code>
   */
  public api.InsertOptionOrBuilder getInsertOptionOrBuilder() {
    if (optionCase_ == 100) {
       return (api.InsertOption) option_;
    }
    return api.InsertOption.getDefaultInstance();
  }

  public static final int UPDATEOPTION_FIELD_NUMBER = 101;
  /**
   * <code>.api.UpdateOption UpdateOption = 101;</code>
   */
  public boolean hasUpdateOption() {
    return optionCase_ == 101;
  }
  /**
   * <code>.api.UpdateOption UpdateOption = 101;</code>
   */
  public api.UpdateOption getUpdateOption() {
    if (optionCase_ == 101) {
       return (api.UpdateOption) option_;
    }
    return api.UpdateOption.getDefaultInstance();
  }
  /**
   * <code>.api.UpdateOption UpdateOption = 101;</code>
   */
  public api.UpdateOptionOrBuilder getUpdateOptionOrBuilder() {
    if (optionCase_ == 101) {
       return (api.UpdateOption) option_;
    }
    return api.UpdateOption.getDefaultInstance();
  }

  public static final int MERGEOPTION_FIELD_NUMBER = 102;
  /**
   * <code>.api.MergeOption MergeOption = 102;</code>
   */
  public boolean hasMergeOption() {
    return optionCase_ == 102;
  }
  /**
   * <code>.api.MergeOption MergeOption = 102;</code>
   */
  public api.MergeOption getMergeOption() {
    if (optionCase_ == 102) {
       return (api.MergeOption) option_;
    }
    return api.MergeOption.getDefaultInstance();
  }
  /**
   * <code>.api.MergeOption MergeOption = 102;</code>
   */
  public api.MergeOptionOrBuilder getMergeOptionOrBuilder() {
    if (optionCase_ == 102) {
       return (api.MergeOption) option_;
    }
    return api.MergeOption.getDefaultInstance();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (session_ != null) {
      output.writeMessage(1, getSession());
    }
    if (!getSchemaNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, schemaName_);
    }
    if (!getTableNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, tableName_);
    }
    if (!getPreSQLBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, preSQL_);
    }
    if (!getPostSQLBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, postSQL_);
    }
    if (timeout_ != 0) {
      output.writeInt32(6, timeout_);
    }
    if (!getEncodingBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 7, encoding_);
    }
    if (!getStagingSchemaBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 8, stagingSchema_);
    }
    if (optionCase_ == 100) {
      output.writeMessage(100, (api.InsertOption) option_);
    }
    if (optionCase_ == 101) {
      output.writeMessage(101, (api.UpdateOption) option_);
    }
    if (optionCase_ == 102) {
      output.writeMessage(102, (api.MergeOption) option_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (session_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getSession());
    }
    if (!getSchemaNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, schemaName_);
    }
    if (!getTableNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, tableName_);
    }
    if (!getPreSQLBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, preSQL_);
    }
    if (!getPostSQLBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, postSQL_);
    }
    if (timeout_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(6, timeout_);
    }
    if (!getEncodingBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, encoding_);
    }
    if (!getStagingSchemaBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, stagingSchema_);
    }
    if (optionCase_ == 100) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(100, (api.InsertOption) option_);
    }
    if (optionCase_ == 101) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(101, (api.UpdateOption) option_);
    }
    if (optionCase_ == 102) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(102, (api.MergeOption) option_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof api.OpenRequest)) {
      return super.equals(obj);
    }
    api.OpenRequest other = (api.OpenRequest) obj;

    boolean result = true;
    result = result && (hasSession() == other.hasSession());
    if (hasSession()) {
      result = result && getSession()
          .equals(other.getSession());
    }
    result = result && getSchemaName()
        .equals(other.getSchemaName());
    result = result && getTableName()
        .equals(other.getTableName());
    result = result && getPreSQL()
        .equals(other.getPreSQL());
    result = result && getPostSQL()
        .equals(other.getPostSQL());
    result = result && (getTimeout()
        == other.getTimeout());
    result = result && getEncoding()
        .equals(other.getEncoding());
    result = result && getStagingSchema()
        .equals(other.getStagingSchema());
    result = result && getOptionCase().equals(
        other.getOptionCase());
    if (!result) return false;
    switch (optionCase_) {
      case 100:
        result = result && getInsertOption()
            .equals(other.getInsertOption());
        break;
      case 101:
        result = result && getUpdateOption()
            .equals(other.getUpdateOption());
        break;
      case 102:
        result = result && getMergeOption()
            .equals(other.getMergeOption());
        break;
      case 0:
      default:
    }
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasSession()) {
      hash = (37 * hash) + SESSION_FIELD_NUMBER;
      hash = (53 * hash) + getSession().hashCode();
    }
    hash = (37 * hash) + SCHEMANAME_FIELD_NUMBER;
    hash = (53 * hash) + getSchemaName().hashCode();
    hash = (37 * hash) + TABLENAME_FIELD_NUMBER;
    hash = (53 * hash) + getTableName().hashCode();
    hash = (37 * hash) + PRESQL_FIELD_NUMBER;
    hash = (53 * hash) + getPreSQL().hashCode();
    hash = (37 * hash) + POSTSQL_FIELD_NUMBER;
    hash = (53 * hash) + getPostSQL().hashCode();
    hash = (37 * hash) + TIMEOUT_FIELD_NUMBER;
    hash = (53 * hash) + getTimeout();
    hash = (37 * hash) + ENCODING_FIELD_NUMBER;
    hash = (53 * hash) + getEncoding().hashCode();
    hash = (37 * hash) + STAGINGSCHEMA_FIELD_NUMBER;
    hash = (53 * hash) + getStagingSchema().hashCode();
    switch (optionCase_) {
      case 100:
        hash = (37 * hash) + INSERTOPTION_FIELD_NUMBER;
        hash = (53 * hash) + getInsertOption().hashCode();
        break;
      case 101:
        hash = (37 * hash) + UPDATEOPTION_FIELD_NUMBER;
        hash = (53 * hash) + getUpdateOption().hashCode();
        break;
      case 102:
        hash = (37 * hash) + MERGEOPTION_FIELD_NUMBER;
        hash = (53 * hash) + getMergeOption().hashCode();
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static api.OpenRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static api.OpenRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static api.OpenRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static api.OpenRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static api.OpenRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static api.OpenRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static api.OpenRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static api.OpenRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static api.OpenRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static api.OpenRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static api.OpenRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static api.OpenRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(api.OpenRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Open service Request message
   * </pre>
   *
   * Protobuf type {@code api.OpenRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:api.OpenRequest)
      api.OpenRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return api.GpssOuterClass.internal_static_api_OpenRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return api.GpssOuterClass.internal_static_api_OpenRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              api.OpenRequest.class, api.OpenRequest.Builder.class);
    }

    // Construct using api.OpenRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (sessionBuilder_ == null) {
        session_ = null;
      } else {
        session_ = null;
        sessionBuilder_ = null;
      }
      schemaName_ = "";

      tableName_ = "";

      preSQL_ = "";

      postSQL_ = "";

      timeout_ = 0;

      encoding_ = "";

      stagingSchema_ = "";

      optionCase_ = 0;
      option_ = null;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return api.GpssOuterClass.internal_static_api_OpenRequest_descriptor;
    }

    @java.lang.Override
    public api.OpenRequest getDefaultInstanceForType() {
      return api.OpenRequest.getDefaultInstance();
    }

    @java.lang.Override
    public api.OpenRequest build() {
      api.OpenRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public api.OpenRequest buildPartial() {
      api.OpenRequest result = new api.OpenRequest(this);
      if (sessionBuilder_ == null) {
        result.session_ = session_;
      } else {
        result.session_ = sessionBuilder_.build();
      }
      result.schemaName_ = schemaName_;
      result.tableName_ = tableName_;
      result.preSQL_ = preSQL_;
      result.postSQL_ = postSQL_;
      result.timeout_ = timeout_;
      result.encoding_ = encoding_;
      result.stagingSchema_ = stagingSchema_;
      if (optionCase_ == 100) {
        if (insertOptionBuilder_ == null) {
          result.option_ = option_;
        } else {
          result.option_ = insertOptionBuilder_.build();
        }
      }
      if (optionCase_ == 101) {
        if (updateOptionBuilder_ == null) {
          result.option_ = option_;
        } else {
          result.option_ = updateOptionBuilder_.build();
        }
      }
      if (optionCase_ == 102) {
        if (mergeOptionBuilder_ == null) {
          result.option_ = option_;
        } else {
          result.option_ = mergeOptionBuilder_.build();
        }
      }
      result.optionCase_ = optionCase_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof api.OpenRequest) {
        return mergeFrom((api.OpenRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(api.OpenRequest other) {
      if (other == api.OpenRequest.getDefaultInstance()) return this;
      if (other.hasSession()) {
        mergeSession(other.getSession());
      }
      if (!other.getSchemaName().isEmpty()) {
        schemaName_ = other.schemaName_;
        onChanged();
      }
      if (!other.getTableName().isEmpty()) {
        tableName_ = other.tableName_;
        onChanged();
      }
      if (!other.getPreSQL().isEmpty()) {
        preSQL_ = other.preSQL_;
        onChanged();
      }
      if (!other.getPostSQL().isEmpty()) {
        postSQL_ = other.postSQL_;
        onChanged();
      }
      if (other.getTimeout() != 0) {
        setTimeout(other.getTimeout());
      }
      if (!other.getEncoding().isEmpty()) {
        encoding_ = other.encoding_;
        onChanged();
      }
      if (!other.getStagingSchema().isEmpty()) {
        stagingSchema_ = other.stagingSchema_;
        onChanged();
      }
      switch (other.getOptionCase()) {
        case INSERTOPTION: {
          mergeInsertOption(other.getInsertOption());
          break;
        }
        case UPDATEOPTION: {
          mergeUpdateOption(other.getUpdateOption());
          break;
        }
        case MERGEOPTION: {
          mergeMergeOption(other.getMergeOption());
          break;
        }
        case OPTION_NOT_SET: {
          break;
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      api.OpenRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (api.OpenRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int optionCase_ = 0;
    private java.lang.Object option_;
    public OptionCase
        getOptionCase() {
      return OptionCase.forNumber(
          optionCase_);
    }

    public Builder clearOption() {
      optionCase_ = 0;
      option_ = null;
      onChanged();
      return this;
    }


    private api.Session session_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        api.Session, api.Session.Builder, api.SessionOrBuilder> sessionBuilder_;
    /**
     * <pre>
     * Session ID returned by Connect
     * </pre>
     *
     * <code>.api.Session Session = 1;</code>
     */
    public boolean hasSession() {
      return sessionBuilder_ != null || session_ != null;
    }
    /**
     * <pre>
     * Session ID returned by Connect
     * </pre>
     *
     * <code>.api.Session Session = 1;</code>
     */
    public api.Session getSession() {
      if (sessionBuilder_ == null) {
        return session_ == null ? api.Session.getDefaultInstance() : session_;
      } else {
        return sessionBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * Session ID returned by Connect
     * </pre>
     *
     * <code>.api.Session Session = 1;</code>
     */
    public Builder setSession(api.Session value) {
      if (sessionBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        session_ = value;
        onChanged();
      } else {
        sessionBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     * Session ID returned by Connect
     * </pre>
     *
     * <code>.api.Session Session = 1;</code>
     */
    public Builder setSession(
        api.Session.Builder builderForValue) {
      if (sessionBuilder_ == null) {
        session_ = builderForValue.build();
        onChanged();
      } else {
        sessionBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     * Session ID returned by Connect
     * </pre>
     *
     * <code>.api.Session Session = 1;</code>
     */
    public Builder mergeSession(api.Session value) {
      if (sessionBuilder_ == null) {
        if (session_ != null) {
          session_ =
            api.Session.newBuilder(session_).mergeFrom(value).buildPartial();
        } else {
          session_ = value;
        }
        onChanged();
      } else {
        sessionBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     * Session ID returned by Connect
     * </pre>
     *
     * <code>.api.Session Session = 1;</code>
     */
    public Builder clearSession() {
      if (sessionBuilder_ == null) {
        session_ = null;
        onChanged();
      } else {
        session_ = null;
        sessionBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     * Session ID returned by Connect
     * </pre>
     *
     * <code>.api.Session Session = 1;</code>
     */
    public api.Session.Builder getSessionBuilder() {
      
      onChanged();
      return getSessionFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * Session ID returned by Connect
     * </pre>
     *
     * <code>.api.Session Session = 1;</code>
     */
    public api.SessionOrBuilder getSessionOrBuilder() {
      if (sessionBuilder_ != null) {
        return sessionBuilder_.getMessageOrBuilder();
      } else {
        return session_ == null ?
            api.Session.getDefaultInstance() : session_;
      }
    }
    /**
     * <pre>
     * Session ID returned by Connect
     * </pre>
     *
     * <code>.api.Session Session = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        api.Session, api.Session.Builder, api.SessionOrBuilder> 
        getSessionFieldBuilder() {
      if (sessionBuilder_ == null) {
        sessionBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            api.Session, api.Session.Builder, api.SessionOrBuilder>(
                getSession(),
                getParentForChildren(),
                isClean());
        session_ = null;
      }
      return sessionBuilder_;
    }

    private java.lang.Object schemaName_ = "";
    /**
     * <pre>
     * Name of the Greenplum Database schema
     * </pre>
     *
     * <code>string SchemaName = 2;</code>
     */
    public java.lang.String getSchemaName() {
      java.lang.Object ref = schemaName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        schemaName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Name of the Greenplum Database schema
     * </pre>
     *
     * <code>string SchemaName = 2;</code>
     */
    public com.google.protobuf.ByteString
        getSchemaNameBytes() {
      java.lang.Object ref = schemaName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        schemaName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Name of the Greenplum Database schema
     * </pre>
     *
     * <code>string SchemaName = 2;</code>
     */
    public Builder setSchemaName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      schemaName_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Name of the Greenplum Database schema
     * </pre>
     *
     * <code>string SchemaName = 2;</code>
     */
    public Builder clearSchemaName() {
      
      schemaName_ = getDefaultInstance().getSchemaName();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Name of the Greenplum Database schema
     * </pre>
     *
     * <code>string SchemaName = 2;</code>
     */
    public Builder setSchemaNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      schemaName_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object tableName_ = "";
    /**
     * <pre>
     * Name of the Greenplum Database table
     * </pre>
     *
     * <code>string TableName = 3;</code>
     */
    public java.lang.String getTableName() {
      java.lang.Object ref = tableName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        tableName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Name of the Greenplum Database table
     * </pre>
     *
     * <code>string TableName = 3;</code>
     */
    public com.google.protobuf.ByteString
        getTableNameBytes() {
      java.lang.Object ref = tableName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        tableName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Name of the Greenplum Database table
     * </pre>
     *
     * <code>string TableName = 3;</code>
     */
    public Builder setTableName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      tableName_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Name of the Greenplum Database table
     * </pre>
     *
     * <code>string TableName = 3;</code>
     */
    public Builder clearTableName() {
      
      tableName_ = getDefaultInstance().getTableName();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Name of the Greenplum Database table
     * </pre>
     *
     * <code>string TableName = 3;</code>
     */
    public Builder setTableNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      tableName_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object preSQL_ = "";
    /**
     * <pre>
     * SQL to execute before gpss loads the data
     * </pre>
     *
     * <code>string PreSQL = 4;</code>
     */
    public java.lang.String getPreSQL() {
      java.lang.Object ref = preSQL_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        preSQL_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * SQL to execute before gpss loads the data
     * </pre>
     *
     * <code>string PreSQL = 4;</code>
     */
    public com.google.protobuf.ByteString
        getPreSQLBytes() {
      java.lang.Object ref = preSQL_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        preSQL_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * SQL to execute before gpss loads the data
     * </pre>
     *
     * <code>string PreSQL = 4;</code>
     */
    public Builder setPreSQL(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      preSQL_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * SQL to execute before gpss loads the data
     * </pre>
     *
     * <code>string PreSQL = 4;</code>
     */
    public Builder clearPreSQL() {
      
      preSQL_ = getDefaultInstance().getPreSQL();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * SQL to execute before gpss loads the data
     * </pre>
     *
     * <code>string PreSQL = 4;</code>
     */
    public Builder setPreSQLBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      preSQL_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object postSQL_ = "";
    /**
     * <pre>
     * SQL to execute after gpss loads the data
     * </pre>
     *
     * <code>string PostSQL = 5;</code>
     */
    public java.lang.String getPostSQL() {
      java.lang.Object ref = postSQL_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        postSQL_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * SQL to execute after gpss loads the data
     * </pre>
     *
     * <code>string PostSQL = 5;</code>
     */
    public com.google.protobuf.ByteString
        getPostSQLBytes() {
      java.lang.Object ref = postSQL_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        postSQL_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * SQL to execute after gpss loads the data
     * </pre>
     *
     * <code>string PostSQL = 5;</code>
     */
    public Builder setPostSQL(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      postSQL_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * SQL to execute after gpss loads the data
     * </pre>
     *
     * <code>string PostSQL = 5;</code>
     */
    public Builder clearPostSQL() {
      
      postSQL_ = getDefaultInstance().getPostSQL();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * SQL to execute after gpss loads the data
     * </pre>
     *
     * <code>string PostSQL = 5;</code>
     */
    public Builder setPostSQLBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      postSQL_ = value;
      onChanged();
      return this;
    }

    private int timeout_ ;
    /**
     * <pre>
     * Time to wait before aborting the operation (seconds); not supported
     * </pre>
     *
     * <code>int32 Timeout = 6;</code>
     */
    public int getTimeout() {
      return timeout_;
    }
    /**
     * <pre>
     * Time to wait before aborting the operation (seconds); not supported
     * </pre>
     *
     * <code>int32 Timeout = 6;</code>
     */
    public Builder setTimeout(int value) {
      
      timeout_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Time to wait before aborting the operation (seconds); not supported
     * </pre>
     *
     * <code>int32 Timeout = 6;</code>
     */
    public Builder clearTimeout() {
      
      timeout_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object encoding_ = "";
    /**
     * <pre>
     * Encoding of text data; not supported
     * </pre>
     *
     * <code>string Encoding = 7;</code>
     */
    public java.lang.String getEncoding() {
      java.lang.Object ref = encoding_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        encoding_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Encoding of text data; not supported
     * </pre>
     *
     * <code>string Encoding = 7;</code>
     */
    public com.google.protobuf.ByteString
        getEncodingBytes() {
      java.lang.Object ref = encoding_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        encoding_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Encoding of text data; not supported
     * </pre>
     *
     * <code>string Encoding = 7;</code>
     */
    public Builder setEncoding(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      encoding_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Encoding of text data; not supported
     * </pre>
     *
     * <code>string Encoding = 7;</code>
     */
    public Builder clearEncoding() {
      
      encoding_ = getDefaultInstance().getEncoding();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Encoding of text data; not supported
     * </pre>
     *
     * <code>string Encoding = 7;</code>
     */
    public Builder setEncodingBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      encoding_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object stagingSchema_ = "";
    /**
     * <pre>
     * Schema in which gpss creates external and temp tables; default is to create these tables in the same schema as the target table
     * </pre>
     *
     * <code>string StagingSchema = 8;</code>
     */
    public java.lang.String getStagingSchema() {
      java.lang.Object ref = stagingSchema_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        stagingSchema_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Schema in which gpss creates external and temp tables; default is to create these tables in the same schema as the target table
     * </pre>
     *
     * <code>string StagingSchema = 8;</code>
     */
    public com.google.protobuf.ByteString
        getStagingSchemaBytes() {
      java.lang.Object ref = stagingSchema_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        stagingSchema_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Schema in which gpss creates external and temp tables; default is to create these tables in the same schema as the target table
     * </pre>
     *
     * <code>string StagingSchema = 8;</code>
     */
    public Builder setStagingSchema(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      stagingSchema_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Schema in which gpss creates external and temp tables; default is to create these tables in the same schema as the target table
     * </pre>
     *
     * <code>string StagingSchema = 8;</code>
     */
    public Builder clearStagingSchema() {
      
      stagingSchema_ = getDefaultInstance().getStagingSchema();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Schema in which gpss creates external and temp tables; default is to create these tables in the same schema as the target table
     * </pre>
     *
     * <code>string StagingSchema = 8;</code>
     */
    public Builder setStagingSchemaBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      stagingSchema_ = value;
      onChanged();
      return this;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        api.InsertOption, api.InsertOption.Builder, api.InsertOptionOrBuilder> insertOptionBuilder_;
    /**
     * <code>.api.InsertOption InsertOption = 100;</code>
     */
    public boolean hasInsertOption() {
      return optionCase_ == 100;
    }
    /**
     * <code>.api.InsertOption InsertOption = 100;</code>
     */
    public api.InsertOption getInsertOption() {
      if (insertOptionBuilder_ == null) {
        if (optionCase_ == 100) {
          return (api.InsertOption) option_;
        }
        return api.InsertOption.getDefaultInstance();
      } else {
        if (optionCase_ == 100) {
          return insertOptionBuilder_.getMessage();
        }
        return api.InsertOption.getDefaultInstance();
      }
    }
    /**
     * <code>.api.InsertOption InsertOption = 100;</code>
     */
    public Builder setInsertOption(api.InsertOption value) {
      if (insertOptionBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        option_ = value;
        onChanged();
      } else {
        insertOptionBuilder_.setMessage(value);
      }
      optionCase_ = 100;
      return this;
    }
    /**
     * <code>.api.InsertOption InsertOption = 100;</code>
     */
    public Builder setInsertOption(
        api.InsertOption.Builder builderForValue) {
      if (insertOptionBuilder_ == null) {
        option_ = builderForValue.build();
        onChanged();
      } else {
        insertOptionBuilder_.setMessage(builderForValue.build());
      }
      optionCase_ = 100;
      return this;
    }
    /**
     * <code>.api.InsertOption InsertOption = 100;</code>
     */
    public Builder mergeInsertOption(api.InsertOption value) {
      if (insertOptionBuilder_ == null) {
        if (optionCase_ == 100 &&
            option_ != api.InsertOption.getDefaultInstance()) {
          option_ = api.InsertOption.newBuilder((api.InsertOption) option_)
              .mergeFrom(value).buildPartial();
        } else {
          option_ = value;
        }
        onChanged();
      } else {
        if (optionCase_ == 100) {
          insertOptionBuilder_.mergeFrom(value);
        }
        insertOptionBuilder_.setMessage(value);
      }
      optionCase_ = 100;
      return this;
    }
    /**
     * <code>.api.InsertOption InsertOption = 100;</code>
     */
    public Builder clearInsertOption() {
      if (insertOptionBuilder_ == null) {
        if (optionCase_ == 100) {
          optionCase_ = 0;
          option_ = null;
          onChanged();
        }
      } else {
        if (optionCase_ == 100) {
          optionCase_ = 0;
          option_ = null;
        }
        insertOptionBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.api.InsertOption InsertOption = 100;</code>
     */
    public api.InsertOption.Builder getInsertOptionBuilder() {
      return getInsertOptionFieldBuilder().getBuilder();
    }
    /**
     * <code>.api.InsertOption InsertOption = 100;</code>
     */
    public api.InsertOptionOrBuilder getInsertOptionOrBuilder() {
      if ((optionCase_ == 100) && (insertOptionBuilder_ != null)) {
        return insertOptionBuilder_.getMessageOrBuilder();
      } else {
        if (optionCase_ == 100) {
          return (api.InsertOption) option_;
        }
        return api.InsertOption.getDefaultInstance();
      }
    }
    /**
     * <code>.api.InsertOption InsertOption = 100;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        api.InsertOption, api.InsertOption.Builder, api.InsertOptionOrBuilder> 
        getInsertOptionFieldBuilder() {
      if (insertOptionBuilder_ == null) {
        if (!(optionCase_ == 100)) {
          option_ = api.InsertOption.getDefaultInstance();
        }
        insertOptionBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            api.InsertOption, api.InsertOption.Builder, api.InsertOptionOrBuilder>(
                (api.InsertOption) option_,
                getParentForChildren(),
                isClean());
        option_ = null;
      }
      optionCase_ = 100;
      onChanged();;
      return insertOptionBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        api.UpdateOption, api.UpdateOption.Builder, api.UpdateOptionOrBuilder> updateOptionBuilder_;
    /**
     * <code>.api.UpdateOption UpdateOption = 101;</code>
     */
    public boolean hasUpdateOption() {
      return optionCase_ == 101;
    }
    /**
     * <code>.api.UpdateOption UpdateOption = 101;</code>
     */
    public api.UpdateOption getUpdateOption() {
      if (updateOptionBuilder_ == null) {
        if (optionCase_ == 101) {
          return (api.UpdateOption) option_;
        }
        return api.UpdateOption.getDefaultInstance();
      } else {
        if (optionCase_ == 101) {
          return updateOptionBuilder_.getMessage();
        }
        return api.UpdateOption.getDefaultInstance();
      }
    }
    /**
     * <code>.api.UpdateOption UpdateOption = 101;</code>
     */
    public Builder setUpdateOption(api.UpdateOption value) {
      if (updateOptionBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        option_ = value;
        onChanged();
      } else {
        updateOptionBuilder_.setMessage(value);
      }
      optionCase_ = 101;
      return this;
    }
    /**
     * <code>.api.UpdateOption UpdateOption = 101;</code>
     */
    public Builder setUpdateOption(
        api.UpdateOption.Builder builderForValue) {
      if (updateOptionBuilder_ == null) {
        option_ = builderForValue.build();
        onChanged();
      } else {
        updateOptionBuilder_.setMessage(builderForValue.build());
      }
      optionCase_ = 101;
      return this;
    }
    /**
     * <code>.api.UpdateOption UpdateOption = 101;</code>
     */
    public Builder mergeUpdateOption(api.UpdateOption value) {
      if (updateOptionBuilder_ == null) {
        if (optionCase_ == 101 &&
            option_ != api.UpdateOption.getDefaultInstance()) {
          option_ = api.UpdateOption.newBuilder((api.UpdateOption) option_)
              .mergeFrom(value).buildPartial();
        } else {
          option_ = value;
        }
        onChanged();
      } else {
        if (optionCase_ == 101) {
          updateOptionBuilder_.mergeFrom(value);
        }
        updateOptionBuilder_.setMessage(value);
      }
      optionCase_ = 101;
      return this;
    }
    /**
     * <code>.api.UpdateOption UpdateOption = 101;</code>
     */
    public Builder clearUpdateOption() {
      if (updateOptionBuilder_ == null) {
        if (optionCase_ == 101) {
          optionCase_ = 0;
          option_ = null;
          onChanged();
        }
      } else {
        if (optionCase_ == 101) {
          optionCase_ = 0;
          option_ = null;
        }
        updateOptionBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.api.UpdateOption UpdateOption = 101;</code>
     */
    public api.UpdateOption.Builder getUpdateOptionBuilder() {
      return getUpdateOptionFieldBuilder().getBuilder();
    }
    /**
     * <code>.api.UpdateOption UpdateOption = 101;</code>
     */
    public api.UpdateOptionOrBuilder getUpdateOptionOrBuilder() {
      if ((optionCase_ == 101) && (updateOptionBuilder_ != null)) {
        return updateOptionBuilder_.getMessageOrBuilder();
      } else {
        if (optionCase_ == 101) {
          return (api.UpdateOption) option_;
        }
        return api.UpdateOption.getDefaultInstance();
      }
    }
    /**
     * <code>.api.UpdateOption UpdateOption = 101;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        api.UpdateOption, api.UpdateOption.Builder, api.UpdateOptionOrBuilder> 
        getUpdateOptionFieldBuilder() {
      if (updateOptionBuilder_ == null) {
        if (!(optionCase_ == 101)) {
          option_ = api.UpdateOption.getDefaultInstance();
        }
        updateOptionBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            api.UpdateOption, api.UpdateOption.Builder, api.UpdateOptionOrBuilder>(
                (api.UpdateOption) option_,
                getParentForChildren(),
                isClean());
        option_ = null;
      }
      optionCase_ = 101;
      onChanged();;
      return updateOptionBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        api.MergeOption, api.MergeOption.Builder, api.MergeOptionOrBuilder> mergeOptionBuilder_;
    /**
     * <code>.api.MergeOption MergeOption = 102;</code>
     */
    public boolean hasMergeOption() {
      return optionCase_ == 102;
    }
    /**
     * <code>.api.MergeOption MergeOption = 102;</code>
     */
    public api.MergeOption getMergeOption() {
      if (mergeOptionBuilder_ == null) {
        if (optionCase_ == 102) {
          return (api.MergeOption) option_;
        }
        return api.MergeOption.getDefaultInstance();
      } else {
        if (optionCase_ == 102) {
          return mergeOptionBuilder_.getMessage();
        }
        return api.MergeOption.getDefaultInstance();
      }
    }
    /**
     * <code>.api.MergeOption MergeOption = 102;</code>
     */
    public Builder setMergeOption(api.MergeOption value) {
      if (mergeOptionBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        option_ = value;
        onChanged();
      } else {
        mergeOptionBuilder_.setMessage(value);
      }
      optionCase_ = 102;
      return this;
    }
    /**
     * <code>.api.MergeOption MergeOption = 102;</code>
     */
    public Builder setMergeOption(
        api.MergeOption.Builder builderForValue) {
      if (mergeOptionBuilder_ == null) {
        option_ = builderForValue.build();
        onChanged();
      } else {
        mergeOptionBuilder_.setMessage(builderForValue.build());
      }
      optionCase_ = 102;
      return this;
    }
    /**
     * <code>.api.MergeOption MergeOption = 102;</code>
     */
    public Builder mergeMergeOption(api.MergeOption value) {
      if (mergeOptionBuilder_ == null) {
        if (optionCase_ == 102 &&
            option_ != api.MergeOption.getDefaultInstance()) {
          option_ = api.MergeOption.newBuilder((api.MergeOption) option_)
              .mergeFrom(value).buildPartial();
        } else {
          option_ = value;
        }
        onChanged();
      } else {
        if (optionCase_ == 102) {
          mergeOptionBuilder_.mergeFrom(value);
        }
        mergeOptionBuilder_.setMessage(value);
      }
      optionCase_ = 102;
      return this;
    }
    /**
     * <code>.api.MergeOption MergeOption = 102;</code>
     */
    public Builder clearMergeOption() {
      if (mergeOptionBuilder_ == null) {
        if (optionCase_ == 102) {
          optionCase_ = 0;
          option_ = null;
          onChanged();
        }
      } else {
        if (optionCase_ == 102) {
          optionCase_ = 0;
          option_ = null;
        }
        mergeOptionBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.api.MergeOption MergeOption = 102;</code>
     */
    public api.MergeOption.Builder getMergeOptionBuilder() {
      return getMergeOptionFieldBuilder().getBuilder();
    }
    /**
     * <code>.api.MergeOption MergeOption = 102;</code>
     */
    public api.MergeOptionOrBuilder getMergeOptionOrBuilder() {
      if ((optionCase_ == 102) && (mergeOptionBuilder_ != null)) {
        return mergeOptionBuilder_.getMessageOrBuilder();
      } else {
        if (optionCase_ == 102) {
          return (api.MergeOption) option_;
        }
        return api.MergeOption.getDefaultInstance();
      }
    }
    /**
     * <code>.api.MergeOption MergeOption = 102;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        api.MergeOption, api.MergeOption.Builder, api.MergeOptionOrBuilder> 
        getMergeOptionFieldBuilder() {
      if (mergeOptionBuilder_ == null) {
        if (!(optionCase_ == 102)) {
          option_ = api.MergeOption.getDefaultInstance();
        }
        mergeOptionBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            api.MergeOption, api.MergeOption.Builder, api.MergeOptionOrBuilder>(
                (api.MergeOption) option_,
                getParentForChildren(),
                isClean());
        option_ = null;
      }
      optionCase_ = 102;
      onChanged();;
      return mergeOptionBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:api.OpenRequest)
  }

  // @@protoc_insertion_point(class_scope:api.OpenRequest)
  private static final api.OpenRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new api.OpenRequest();
  }

  public static api.OpenRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<OpenRequest>
      PARSER = new com.google.protobuf.AbstractParser<OpenRequest>() {
    @java.lang.Override
    public OpenRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new OpenRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<OpenRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<OpenRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public api.OpenRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

