// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gpss.proto

package api;

public interface OpenRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:api.OpenRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Session ID returned by Connect
   * </pre>
   *
   * <code>.api.Session Session = 1;</code>
   */
  boolean hasSession();
  /**
   * <pre>
   * Session ID returned by Connect
   * </pre>
   *
   * <code>.api.Session Session = 1;</code>
   */
  api.Session getSession();
  /**
   * <pre>
   * Session ID returned by Connect
   * </pre>
   *
   * <code>.api.Session Session = 1;</code>
   */
  api.SessionOrBuilder getSessionOrBuilder();

  /**
   * <pre>
   * Name of the Greenplum Database schema
   * </pre>
   *
   * <code>string SchemaName = 2;</code>
   */
  java.lang.String getSchemaName();
  /**
   * <pre>
   * Name of the Greenplum Database schema
   * </pre>
   *
   * <code>string SchemaName = 2;</code>
   */
  com.google.protobuf.ByteString
      getSchemaNameBytes();

  /**
   * <pre>
   * Name of the Greenplum Database table
   * </pre>
   *
   * <code>string TableName = 3;</code>
   */
  java.lang.String getTableName();
  /**
   * <pre>
   * Name of the Greenplum Database table
   * </pre>
   *
   * <code>string TableName = 3;</code>
   */
  com.google.protobuf.ByteString
      getTableNameBytes();

  /**
   * <pre>
   * SQL to execute before gpss loads the data
   * </pre>
   *
   * <code>string PreSQL = 4;</code>
   */
  java.lang.String getPreSQL();
  /**
   * <pre>
   * SQL to execute before gpss loads the data
   * </pre>
   *
   * <code>string PreSQL = 4;</code>
   */
  com.google.protobuf.ByteString
      getPreSQLBytes();

  /**
   * <pre>
   * SQL to execute after gpss loads the data
   * </pre>
   *
   * <code>string PostSQL = 5;</code>
   */
  java.lang.String getPostSQL();
  /**
   * <pre>
   * SQL to execute after gpss loads the data
   * </pre>
   *
   * <code>string PostSQL = 5;</code>
   */
  com.google.protobuf.ByteString
      getPostSQLBytes();

  /**
   * <pre>
   * Time to wait before aborting the operation (seconds); not supported
   * </pre>
   *
   * <code>int32 Timeout = 6;</code>
   */
  int getTimeout();

  /**
   * <pre>
   * Encoding of text data; not supported
   * </pre>
   *
   * <code>string Encoding = 7;</code>
   */
  java.lang.String getEncoding();
  /**
   * <pre>
   * Encoding of text data; not supported
   * </pre>
   *
   * <code>string Encoding = 7;</code>
   */
  com.google.protobuf.ByteString
      getEncodingBytes();

  /**
   * <pre>
   * Schema in which gpss creates external and temp tables; default is to create these tables in the same schema as the target table
   * </pre>
   *
   * <code>string StagingSchema = 8;</code>
   */
  java.lang.String getStagingSchema();
  /**
   * <pre>
   * Schema in which gpss creates external and temp tables; default is to create these tables in the same schema as the target table
   * </pre>
   *
   * <code>string StagingSchema = 8;</code>
   */
  com.google.protobuf.ByteString
      getStagingSchemaBytes();

  /**
   * <code>.api.InsertOption InsertOption = 100;</code>
   */
  boolean hasInsertOption();
  /**
   * <code>.api.InsertOption InsertOption = 100;</code>
   */
  api.InsertOption getInsertOption();
  /**
   * <code>.api.InsertOption InsertOption = 100;</code>
   */
  api.InsertOptionOrBuilder getInsertOptionOrBuilder();

  /**
   * <code>.api.UpdateOption UpdateOption = 101;</code>
   */
  boolean hasUpdateOption();
  /**
   * <code>.api.UpdateOption UpdateOption = 101;</code>
   */
  api.UpdateOption getUpdateOption();
  /**
   * <code>.api.UpdateOption UpdateOption = 101;</code>
   */
  api.UpdateOptionOrBuilder getUpdateOptionOrBuilder();

  /**
   * <code>.api.MergeOption MergeOption = 102;</code>
   */
  boolean hasMergeOption();
  /**
   * <code>.api.MergeOption MergeOption = 102;</code>
   */
  api.MergeOption getMergeOption();
  /**
   * <code>.api.MergeOption MergeOption = 102;</code>
   */
  api.MergeOptionOrBuilder getMergeOptionOrBuilder();

  public api.OpenRequest.OptionCase getOptionCase();
}
