// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gpss.proto

package api;

public interface RowOrBuilder extends
    // @@protoc_insertion_point(interface_extends:api.Row)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .api.DBValue Columns = 1;</code>
   */
  java.util.List<api.DBValue> 
      getColumnsList();
  /**
   * <code>repeated .api.DBValue Columns = 1;</code>
   */
  api.DBValue getColumns(int index);
  /**
   * <code>repeated .api.DBValue Columns = 1;</code>
   */
  int getColumnsCount();
  /**
   * <code>repeated .api.DBValue Columns = 1;</code>
   */
  java.util.List<? extends api.DBValueOrBuilder> 
      getColumnsOrBuilderList();
  /**
   * <code>repeated .api.DBValue Columns = 1;</code>
   */
  api.DBValueOrBuilder getColumnsOrBuilder(
      int index);
}
