// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gpss.proto

package api;

public interface SchemasOrBuilder extends
    // @@protoc_insertion_point(interface_extends:api.Schemas)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .api.Schema Schemas = 1;</code>
   */
  java.util.List<api.Schema> 
      getSchemasList();
  /**
   * <code>repeated .api.Schema Schemas = 1;</code>
   */
  api.Schema getSchemas(int index);
  /**
   * <code>repeated .api.Schema Schemas = 1;</code>
   */
  int getSchemasCount();
  /**
   * <code>repeated .api.Schema Schemas = 1;</code>
   */
  java.util.List<? extends api.SchemaOrBuilder> 
      getSchemasOrBuilderList();
  /**
   * <code>repeated .api.Schema Schemas = 1;</code>
   */
  api.SchemaOrBuilder getSchemasOrBuilder(
      int index);
}
