// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gpss.proto

package api;

public interface SchemaOrBuilder extends
    // @@protoc_insertion_point(interface_extends:api.Schema)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string Name = 1;</code>
   */
  java.lang.String getName();
  /**
   * <code>string Name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string Owner = 2;</code>
   */
  java.lang.String getOwner();
  /**
   * <code>string Owner = 2;</code>
   */
  com.google.protobuf.ByteString
      getOwnerBytes();
}
