// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gpss.proto

package api;

public interface SessionOrBuilder extends
    // @@protoc_insertion_point(interface_extends:api.Session)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Id of client connection to gpss
   * </pre>
   *
   * <code>string ID = 1;</code>
   */
  java.lang.String getID();
  /**
   * <pre>
   * Id of client connection to gpss
   * </pre>
   *
   * <code>string ID = 1;</code>
   */
  com.google.protobuf.ByteString
      getIDBytes();
}
