// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gpss.proto

package api;

public interface TableInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:api.TableInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string Name = 1;</code>
   */
  java.lang.String getName();
  /**
   * <code>string Name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>.api.RelationType Type = 2;</code>
   */
  int getTypeValue();
  /**
   * <code>.api.RelationType Type = 2;</code>
   */
  api.RelationType getType();
}
