// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gpss.proto

package api;

public interface TablesOrBuilder extends
    // @@protoc_insertion_point(interface_extends:api.Tables)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .api.TableInfo Tables = 1;</code>
   */
  java.util.List<api.TableInfo> 
      getTablesList();
  /**
   * <code>repeated .api.TableInfo Tables = 1;</code>
   */
  api.TableInfo getTables(int index);
  /**
   * <code>repeated .api.TableInfo Tables = 1;</code>
   */
  int getTablesCount();
  /**
   * <code>repeated .api.TableInfo Tables = 1;</code>
   */
  java.util.List<? extends api.TableInfoOrBuilder> 
      getTablesOrBuilderList();
  /**
   * <code>repeated .api.TableInfo Tables = 1;</code>
   */
  api.TableInfoOrBuilder getTablesOrBuilder(
      int index);
}
