// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gpss.proto

package api;

/**
 * <pre>
 * Required parameters of the Update operation
 * </pre>
 *
 * Protobuf type {@code api.UpdateOption}
 */
public  final class UpdateOption extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:api.UpdateOption)
    UpdateOptionOrBuilder {
private static final long serialVersionUID = 0L;
  // Use UpdateOption.newBuilder() to construct.
  private UpdateOption(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private UpdateOption() {
    matchColumns_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    updateColumns_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    condition_ = "";
    errorLimitCount_ = 0L;
    errorLimitPercentage_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private UpdateOption(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
              matchColumns_ = new com.google.protobuf.LazyStringArrayList();
              mutable_bitField0_ |= 0x00000001;
            }
            matchColumns_.add(s);
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();
            if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
              updateColumns_ = new com.google.protobuf.LazyStringArrayList();
              mutable_bitField0_ |= 0x00000002;
            }
            updateColumns_.add(s);
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            condition_ = s;
            break;
          }
          case 32: {

            errorLimitCount_ = input.readInt64();
            break;
          }
          case 40: {

            errorLimitPercentage_ = input.readInt32();
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
        matchColumns_ = matchColumns_.getUnmodifiableView();
      }
      if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
        updateColumns_ = updateColumns_.getUnmodifiableView();
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return api.GpssOuterClass.internal_static_api_UpdateOption_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return api.GpssOuterClass.internal_static_api_UpdateOption_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            api.UpdateOption.class, api.UpdateOption.Builder.class);
  }

  private int bitField0_;
  public static final int MATCHCOLUMNS_FIELD_NUMBER = 1;
  private com.google.protobuf.LazyStringList matchColumns_;
  /**
   * <pre>
   * Names of the target table columns to compare when determining to update or not
   * </pre>
   *
   * <code>repeated string MatchColumns = 1;</code>
   */
  public com.google.protobuf.ProtocolStringList
      getMatchColumnsList() {
    return matchColumns_;
  }
  /**
   * <pre>
   * Names of the target table columns to compare when determining to update or not
   * </pre>
   *
   * <code>repeated string MatchColumns = 1;</code>
   */
  public int getMatchColumnsCount() {
    return matchColumns_.size();
  }
  /**
   * <pre>
   * Names of the target table columns to compare when determining to update or not
   * </pre>
   *
   * <code>repeated string MatchColumns = 1;</code>
   */
  public java.lang.String getMatchColumns(int index) {
    return matchColumns_.get(index);
  }
  /**
   * <pre>
   * Names of the target table columns to compare when determining to update or not
   * </pre>
   *
   * <code>repeated string MatchColumns = 1;</code>
   */
  public com.google.protobuf.ByteString
      getMatchColumnsBytes(int index) {
    return matchColumns_.getByteString(index);
  }

  public static final int UPDATECOLUMNS_FIELD_NUMBER = 2;
  private com.google.protobuf.LazyStringList updateColumns_;
  /**
   * <pre>
   * Names of the target table columns to update if MatchColumns match
   * </pre>
   *
   * <code>repeated string UpdateColumns = 2;</code>
   */
  public com.google.protobuf.ProtocolStringList
      getUpdateColumnsList() {
    return updateColumns_;
  }
  /**
   * <pre>
   * Names of the target table columns to update if MatchColumns match
   * </pre>
   *
   * <code>repeated string UpdateColumns = 2;</code>
   */
  public int getUpdateColumnsCount() {
    return updateColumns_.size();
  }
  /**
   * <pre>
   * Names of the target table columns to update if MatchColumns match
   * </pre>
   *
   * <code>repeated string UpdateColumns = 2;</code>
   */
  public java.lang.String getUpdateColumns(int index) {
    return updateColumns_.get(index);
  }
  /**
   * <pre>
   * Names of the target table columns to update if MatchColumns match
   * </pre>
   *
   * <code>repeated string UpdateColumns = 2;</code>
   */
  public com.google.protobuf.ByteString
      getUpdateColumnsBytes(int index) {
    return updateColumns_.getByteString(index);
  }

  public static final int CONDITION_FIELD_NUMBER = 3;
  private volatile java.lang.Object condition_;
  /**
   * <pre>
   * Optional additional match condition; SQL syntax and used after the 'WHERE' clause
   * </pre>
   *
   * <code>string Condition = 3;</code>
   */
  public java.lang.String getCondition() {
    java.lang.Object ref = condition_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      condition_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Optional additional match condition; SQL syntax and used after the 'WHERE' clause
   * </pre>
   *
   * <code>string Condition = 3;</code>
   */
  public com.google.protobuf.ByteString
      getConditionBytes() {
    java.lang.Object ref = condition_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      condition_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ERRORLIMITCOUNT_FIELD_NUMBER = 4;
  private long errorLimitCount_;
  /**
   * <pre>
   * Error limit count; used by external table
   * </pre>
   *
   * <code>int64 ErrorLimitCount = 4;</code>
   */
  public long getErrorLimitCount() {
    return errorLimitCount_;
  }

  public static final int ERRORLIMITPERCENTAGE_FIELD_NUMBER = 5;
  private int errorLimitPercentage_;
  /**
   * <pre>
   * Error limit percentage; used by external table
   * </pre>
   *
   * <code>int32 ErrorLimitPercentage = 5;</code>
   */
  public int getErrorLimitPercentage() {
    return errorLimitPercentage_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < matchColumns_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, matchColumns_.getRaw(i));
    }
    for (int i = 0; i < updateColumns_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, updateColumns_.getRaw(i));
    }
    if (!getConditionBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, condition_);
    }
    if (errorLimitCount_ != 0L) {
      output.writeInt64(4, errorLimitCount_);
    }
    if (errorLimitPercentage_ != 0) {
      output.writeInt32(5, errorLimitPercentage_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    {
      int dataSize = 0;
      for (int i = 0; i < matchColumns_.size(); i++) {
        dataSize += computeStringSizeNoTag(matchColumns_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getMatchColumnsList().size();
    }
    {
      int dataSize = 0;
      for (int i = 0; i < updateColumns_.size(); i++) {
        dataSize += computeStringSizeNoTag(updateColumns_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getUpdateColumnsList().size();
    }
    if (!getConditionBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, condition_);
    }
    if (errorLimitCount_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(4, errorLimitCount_);
    }
    if (errorLimitPercentage_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(5, errorLimitPercentage_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof api.UpdateOption)) {
      return super.equals(obj);
    }
    api.UpdateOption other = (api.UpdateOption) obj;

    boolean result = true;
    result = result && getMatchColumnsList()
        .equals(other.getMatchColumnsList());
    result = result && getUpdateColumnsList()
        .equals(other.getUpdateColumnsList());
    result = result && getCondition()
        .equals(other.getCondition());
    result = result && (getErrorLimitCount()
        == other.getErrorLimitCount());
    result = result && (getErrorLimitPercentage()
        == other.getErrorLimitPercentage());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getMatchColumnsCount() > 0) {
      hash = (37 * hash) + MATCHCOLUMNS_FIELD_NUMBER;
      hash = (53 * hash) + getMatchColumnsList().hashCode();
    }
    if (getUpdateColumnsCount() > 0) {
      hash = (37 * hash) + UPDATECOLUMNS_FIELD_NUMBER;
      hash = (53 * hash) + getUpdateColumnsList().hashCode();
    }
    hash = (37 * hash) + CONDITION_FIELD_NUMBER;
    hash = (53 * hash) + getCondition().hashCode();
    hash = (37 * hash) + ERRORLIMITCOUNT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getErrorLimitCount());
    hash = (37 * hash) + ERRORLIMITPERCENTAGE_FIELD_NUMBER;
    hash = (53 * hash) + getErrorLimitPercentage();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static api.UpdateOption parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static api.UpdateOption parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static api.UpdateOption parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static api.UpdateOption parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static api.UpdateOption parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static api.UpdateOption parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static api.UpdateOption parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static api.UpdateOption parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static api.UpdateOption parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static api.UpdateOption parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static api.UpdateOption parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static api.UpdateOption parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(api.UpdateOption prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Required parameters of the Update operation
   * </pre>
   *
   * Protobuf type {@code api.UpdateOption}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:api.UpdateOption)
      api.UpdateOptionOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return api.GpssOuterClass.internal_static_api_UpdateOption_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return api.GpssOuterClass.internal_static_api_UpdateOption_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              api.UpdateOption.class, api.UpdateOption.Builder.class);
    }

    // Construct using api.UpdateOption.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      matchColumns_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      updateColumns_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000002);
      condition_ = "";

      errorLimitCount_ = 0L;

      errorLimitPercentage_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return api.GpssOuterClass.internal_static_api_UpdateOption_descriptor;
    }

    @java.lang.Override
    public api.UpdateOption getDefaultInstanceForType() {
      return api.UpdateOption.getDefaultInstance();
    }

    @java.lang.Override
    public api.UpdateOption build() {
      api.UpdateOption result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public api.UpdateOption buildPartial() {
      api.UpdateOption result = new api.UpdateOption(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        matchColumns_ = matchColumns_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000001);
      }
      result.matchColumns_ = matchColumns_;
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        updateColumns_ = updateColumns_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000002);
      }
      result.updateColumns_ = updateColumns_;
      result.condition_ = condition_;
      result.errorLimitCount_ = errorLimitCount_;
      result.errorLimitPercentage_ = errorLimitPercentage_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof api.UpdateOption) {
        return mergeFrom((api.UpdateOption)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(api.UpdateOption other) {
      if (other == api.UpdateOption.getDefaultInstance()) return this;
      if (!other.matchColumns_.isEmpty()) {
        if (matchColumns_.isEmpty()) {
          matchColumns_ = other.matchColumns_;
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          ensureMatchColumnsIsMutable();
          matchColumns_.addAll(other.matchColumns_);
        }
        onChanged();
      }
      if (!other.updateColumns_.isEmpty()) {
        if (updateColumns_.isEmpty()) {
          updateColumns_ = other.updateColumns_;
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          ensureUpdateColumnsIsMutable();
          updateColumns_.addAll(other.updateColumns_);
        }
        onChanged();
      }
      if (!other.getCondition().isEmpty()) {
        condition_ = other.condition_;
        onChanged();
      }
      if (other.getErrorLimitCount() != 0L) {
        setErrorLimitCount(other.getErrorLimitCount());
      }
      if (other.getErrorLimitPercentage() != 0) {
        setErrorLimitPercentage(other.getErrorLimitPercentage());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      api.UpdateOption parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (api.UpdateOption) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.LazyStringList matchColumns_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureMatchColumnsIsMutable() {
      if (!((bitField0_ & 0x00000001) == 0x00000001)) {
        matchColumns_ = new com.google.protobuf.LazyStringArrayList(matchColumns_);
        bitField0_ |= 0x00000001;
       }
    }
    /**
     * <pre>
     * Names of the target table columns to compare when determining to update or not
     * </pre>
     *
     * <code>repeated string MatchColumns = 1;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getMatchColumnsList() {
      return matchColumns_.getUnmodifiableView();
    }
    /**
     * <pre>
     * Names of the target table columns to compare when determining to update or not
     * </pre>
     *
     * <code>repeated string MatchColumns = 1;</code>
     */
    public int getMatchColumnsCount() {
      return matchColumns_.size();
    }
    /**
     * <pre>
     * Names of the target table columns to compare when determining to update or not
     * </pre>
     *
     * <code>repeated string MatchColumns = 1;</code>
     */
    public java.lang.String getMatchColumns(int index) {
      return matchColumns_.get(index);
    }
    /**
     * <pre>
     * Names of the target table columns to compare when determining to update or not
     * </pre>
     *
     * <code>repeated string MatchColumns = 1;</code>
     */
    public com.google.protobuf.ByteString
        getMatchColumnsBytes(int index) {
      return matchColumns_.getByteString(index);
    }
    /**
     * <pre>
     * Names of the target table columns to compare when determining to update or not
     * </pre>
     *
     * <code>repeated string MatchColumns = 1;</code>
     */
    public Builder setMatchColumns(
        int index, java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureMatchColumnsIsMutable();
      matchColumns_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Names of the target table columns to compare when determining to update or not
     * </pre>
     *
     * <code>repeated string MatchColumns = 1;</code>
     */
    public Builder addMatchColumns(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureMatchColumnsIsMutable();
      matchColumns_.add(value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Names of the target table columns to compare when determining to update or not
     * </pre>
     *
     * <code>repeated string MatchColumns = 1;</code>
     */
    public Builder addAllMatchColumns(
        java.lang.Iterable<java.lang.String> values) {
      ensureMatchColumnsIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, matchColumns_);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Names of the target table columns to compare when determining to update or not
     * </pre>
     *
     * <code>repeated string MatchColumns = 1;</code>
     */
    public Builder clearMatchColumns() {
      matchColumns_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Names of the target table columns to compare when determining to update or not
     * </pre>
     *
     * <code>repeated string MatchColumns = 1;</code>
     */
    public Builder addMatchColumnsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      ensureMatchColumnsIsMutable();
      matchColumns_.add(value);
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringList updateColumns_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureUpdateColumnsIsMutable() {
      if (!((bitField0_ & 0x00000002) == 0x00000002)) {
        updateColumns_ = new com.google.protobuf.LazyStringArrayList(updateColumns_);
        bitField0_ |= 0x00000002;
       }
    }
    /**
     * <pre>
     * Names of the target table columns to update if MatchColumns match
     * </pre>
     *
     * <code>repeated string UpdateColumns = 2;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getUpdateColumnsList() {
      return updateColumns_.getUnmodifiableView();
    }
    /**
     * <pre>
     * Names of the target table columns to update if MatchColumns match
     * </pre>
     *
     * <code>repeated string UpdateColumns = 2;</code>
     */
    public int getUpdateColumnsCount() {
      return updateColumns_.size();
    }
    /**
     * <pre>
     * Names of the target table columns to update if MatchColumns match
     * </pre>
     *
     * <code>repeated string UpdateColumns = 2;</code>
     */
    public java.lang.String getUpdateColumns(int index) {
      return updateColumns_.get(index);
    }
    /**
     * <pre>
     * Names of the target table columns to update if MatchColumns match
     * </pre>
     *
     * <code>repeated string UpdateColumns = 2;</code>
     */
    public com.google.protobuf.ByteString
        getUpdateColumnsBytes(int index) {
      return updateColumns_.getByteString(index);
    }
    /**
     * <pre>
     * Names of the target table columns to update if MatchColumns match
     * </pre>
     *
     * <code>repeated string UpdateColumns = 2;</code>
     */
    public Builder setUpdateColumns(
        int index, java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureUpdateColumnsIsMutable();
      updateColumns_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Names of the target table columns to update if MatchColumns match
     * </pre>
     *
     * <code>repeated string UpdateColumns = 2;</code>
     */
    public Builder addUpdateColumns(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureUpdateColumnsIsMutable();
      updateColumns_.add(value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Names of the target table columns to update if MatchColumns match
     * </pre>
     *
     * <code>repeated string UpdateColumns = 2;</code>
     */
    public Builder addAllUpdateColumns(
        java.lang.Iterable<java.lang.String> values) {
      ensureUpdateColumnsIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, updateColumns_);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Names of the target table columns to update if MatchColumns match
     * </pre>
     *
     * <code>repeated string UpdateColumns = 2;</code>
     */
    public Builder clearUpdateColumns() {
      updateColumns_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Names of the target table columns to update if MatchColumns match
     * </pre>
     *
     * <code>repeated string UpdateColumns = 2;</code>
     */
    public Builder addUpdateColumnsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      ensureUpdateColumnsIsMutable();
      updateColumns_.add(value);
      onChanged();
      return this;
    }

    private java.lang.Object condition_ = "";
    /**
     * <pre>
     * Optional additional match condition; SQL syntax and used after the 'WHERE' clause
     * </pre>
     *
     * <code>string Condition = 3;</code>
     */
    public java.lang.String getCondition() {
      java.lang.Object ref = condition_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        condition_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Optional additional match condition; SQL syntax and used after the 'WHERE' clause
     * </pre>
     *
     * <code>string Condition = 3;</code>
     */
    public com.google.protobuf.ByteString
        getConditionBytes() {
      java.lang.Object ref = condition_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        condition_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Optional additional match condition; SQL syntax and used after the 'WHERE' clause
     * </pre>
     *
     * <code>string Condition = 3;</code>
     */
    public Builder setCondition(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      condition_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Optional additional match condition; SQL syntax and used after the 'WHERE' clause
     * </pre>
     *
     * <code>string Condition = 3;</code>
     */
    public Builder clearCondition() {
      
      condition_ = getDefaultInstance().getCondition();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Optional additional match condition; SQL syntax and used after the 'WHERE' clause
     * </pre>
     *
     * <code>string Condition = 3;</code>
     */
    public Builder setConditionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      condition_ = value;
      onChanged();
      return this;
    }

    private long errorLimitCount_ ;
    /**
     * <pre>
     * Error limit count; used by external table
     * </pre>
     *
     * <code>int64 ErrorLimitCount = 4;</code>
     */
    public long getErrorLimitCount() {
      return errorLimitCount_;
    }
    /**
     * <pre>
     * Error limit count; used by external table
     * </pre>
     *
     * <code>int64 ErrorLimitCount = 4;</code>
     */
    public Builder setErrorLimitCount(long value) {
      
      errorLimitCount_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Error limit count; used by external table
     * </pre>
     *
     * <code>int64 ErrorLimitCount = 4;</code>
     */
    public Builder clearErrorLimitCount() {
      
      errorLimitCount_ = 0L;
      onChanged();
      return this;
    }

    private int errorLimitPercentage_ ;
    /**
     * <pre>
     * Error limit percentage; used by external table
     * </pre>
     *
     * <code>int32 ErrorLimitPercentage = 5;</code>
     */
    public int getErrorLimitPercentage() {
      return errorLimitPercentage_;
    }
    /**
     * <pre>
     * Error limit percentage; used by external table
     * </pre>
     *
     * <code>int32 ErrorLimitPercentage = 5;</code>
     */
    public Builder setErrorLimitPercentage(int value) {
      
      errorLimitPercentage_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Error limit percentage; used by external table
     * </pre>
     *
     * <code>int32 ErrorLimitPercentage = 5;</code>
     */
    public Builder clearErrorLimitPercentage() {
      
      errorLimitPercentage_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:api.UpdateOption)
  }

  // @@protoc_insertion_point(class_scope:api.UpdateOption)
  private static final api.UpdateOption DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new api.UpdateOption();
  }

  public static api.UpdateOption getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<UpdateOption>
      PARSER = new com.google.protobuf.AbstractParser<UpdateOption>() {
    @java.lang.Override
    public UpdateOption parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new UpdateOption(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<UpdateOption> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<UpdateOption> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public api.UpdateOption getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

